import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import { Toaster } from "sonner";
import localFont from "next/font/local"

// ✅ define kefa locally, NOT exported
const kefa = localFont({
  src: "fonts/kefa-bold.ttf",
  variable: "--font-kefa",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={kefa.variable}>
      <body className={`${kefa.variable} antialiased`}>
        <ClerkProvider 
          appearance={{ baseTheme: dark }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster theme="system" position="bottom-right" />
            {children}
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
